### ISSUE TITLE
Question out of curiosity while evaluating Troubleshoot.sh

### ISSUE THREAD

**Issue by shuknk8s** [replicatedhq/troubleshoot.sh#326]
For running preflight and collectors against Cloud/Remote Database or other Cloud Provider specific services , can I safely assume the database is remote and running on the cloud providers, just wanted to make sure we are not mandating the customer to run the database or similar services in the kubernetes cluster although it is an option with statefulset/deamonset but customers prefer to run those services as cloud provider managed service. Can you please point me to an example for better clarity, sorry for the naive questions as I am just kick starting the journey

**Comment by marccampbell** [comment]
Correct. The troubleshoot project connects to the database using the URI or credentials provided, and does not make any assumptions about the location or infrastructure running the database instance. We've seen it used with RDS instances and other external databases. 

For example:

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sample
spec:
  collectors:
    - postgres:
        collectorName: pg
        uri: postgresql://user:password@<something>.us-east-1.rds.amazonaws.com:5432/mydatabase?sslmode=require
```

The URI can be retrieved from the AWS console. An example of how to find it is here: https://medium.com/exampro/how-to-create-and-connect-an-rds-postgres-database-to-tableplus-terminal-or-rails-app-77d51cc9c18c
