### ISSUE TITLE
Auto ClusterResources Collector Doesn't Respect Spec

### ISSUE THREAD

**Issue by trungng92** [replicatedhq/troubleshoot.sh#531]
Hello, I'm trying to run the ClusterResources within a small subset of namespaces, but am seeing issues with this.

Based on the docs, clusterResources are always included:

https://troubleshoot.sh/docs/collect/cluster-resources/
> This collector is a default collector and it will be automatically included in your collector spec if you don't include it. This collector cannot be removed.

This statement suggests that if you don't include a collector yourself, then it will use the default (which will collects from all namespaces), and if you do include the clusterResource, it will use that configuration.

I tried modifying the tutorial to use the clusterResources on a subset of namespaces, but it still captured data from all namespaces.

```
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: supportbundle-tutorial
spec:
  collectors:
    - clusterResources:
      namespaces:
      - kube-system
      - default
  analyzers: []
```

Support bundle files:

```
support-bundle-empty/cluster-resources/endpoints
support-bundle-empty/cluster-resources/endpoints/default.json
support-bundle-empty/cluster-resources/endpoints/kube-node-lease.json
support-bundle-empty/cluster-resources/endpoints/kube-public.json
support-bundle-empty/cluster-resources/endpoints/kube-system.json
support-bundle-empty/cluster-resources/endpoints/trung.json
```

Version:
```
~/sandbox/troubleshoot.sh ᐅ kubectl support-bundle version
Replicated Troubleshoot 0.78.0
```

**Comment by trungng92** [comment]
Nevermind, the issue was yaml spacing 🥲.

I had this:
```yaml
  collectors:
    - clusterResources:
      namespaces:
      - kube-system
      - default
```
Which created this:
```json
{
  "collectors": [
    {
      "clusterResources": null,
      "namespaces": [
        "kube-system",
        "default"
      ]
    }
  ]
}
```

But needed the part after the collector to be tabbed extra:
```yaml
  collectors:
  - clusterResources:
      namespaces:
      - kube-system
      - default
```

Which creates this (notice that clusterResources is an object here, but in the previous json object is a null value):
```json
{
  "collectors": [
    {
      "clusterResources": {
        "namespaces": [
          "kube-system",
          "default"
        ]
      }
    }
  ]
}
```
